version: '3.8'

services:
  arangodb:
    image: arangodb:3.12.4
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=ph
      # RocksDB optimizations
      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=96G  # Adjust based on your system memory
      - ARANGODB_ROCKSDB_BLOCK_CACHE_SIZE=32G       # ~1/3 of total memory
      - ARANGODB_ROCKSDB_WRITE_BUFFER_SIZE=512M     # Larger write buffer for bulk imports
      - ARANGODB_ROCKSDB_MAX_WRITE_BUFFER_NUMBER=4
      - ARANGODB_ROCKSDB_TOTAL_WRITE_BUFFER_SIZE=2G
      # Query optimizations
      - ARANGODB_QUERY_MEMORY_LIMIT=32G             # Memory limit for queries
    volumes:
      - ./arangodb_data:/var/lib/arangodb3
      - ./arangodb_apps:/var/lib/arangodb3-apps
    deploy:
      resources:
        limits:
          memory: 96G
        reservations:
          memory: 16G
    ulimits:
      nofile:
        soft: 131072
        hard: 131072
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_api/version", "-u", "root:ph"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
